version: '3'
services:
  dashboard:
    build: .
    container_name: spilboard
    restart: unless-stopped
    ports:
      - "80:80"  # change port if needed ("8080:80")
    volumes:
      # where data saves
      - ./data:/app/data