version: '3'
services:
  dashboard:
    image: spiley/spilboard-dashboard:latest
    container_name: spilboard-dashboard
    restart: unless-stopped
    # Privileged is needed for CPU/RAM/Temp stats
    privileged: true
    ports:
      - "80:80" #change if needed (ie. 8080:80)
    volumes:
      # settingsdata
      - ./data:/app/data